require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 20

Naming/MethodParameterName:
  MinNameLength: 1

Style/Documentation:
  Enabled: false